OnlineJobPortalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from portal.forms import UserLoginForm
from portal.views import (
    banner_page,
    jobseeker_register,
    employer_register,
    login_request,
    home_page,
    job_detail,
    search,
    filter_by_category
)



urlpatterns = [
    path('emoloyer/', include('employer.urls')),
    path('user/', include('jobseeker.urls')),
    path('', banner_page, name='banner-page'),
    path('job/list/', home_page, name='home-page'),
    path('admin/', admin.site.urls),
    path('register/', jobseeker_register, name='register'),
    path('employer/register/', employer_register, name='employer-register'),
    path('login/', login_request, name='login'),
    path('job/detail/<int:id>/', job_detail, name='job-detail'),
    path('search/', search, name='search'),
    path('filter/category/<category>', filter_by_category, name='filter-by-category'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

employer/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView



from .views import (employer_home,
                   employer_profile,
                   employer_jobs,
                   employer_create_job,
                   accepted_status,
                   hired_status,
                   delete_request,
                   )


urlpatterns = [
    path('home/', employer_home , name='employer-home'),
    path('profile/', employer_profile , name='employer-profile'),
    path('jobs/', employer_jobs , name='employer-jobs'),
    path('create/job/', employer_create_job , name='employer-create-job'),
    path('accept/request/<int:id>/', accepted_status, name='accept-status'),
    path('hire/request/<int:id>/', hired_status, name='hire-status'),
    path('delete/request/<int:id>/', delete_request, name='delete-request'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

jobseeker/urls.py
from django.urls import path

from .views import (
    jobseeker_profile,
    request_job,
    jobseeker_requests, 
    save_job,
    jobseeker_saved_jobs,
    cancel_request,
)

urlpatterns = [
    path('profile/', jobseeker_profile, name='jobseeker-profile'),
    path('request/job/<id>/', request_job, name='request-job'),
    path('requests/', jobseeker_requests, name='jobseeker-requests'),
    path('save/job/<id>/', save_job, name='save-job'),
    path('saved/', jobseeker_saved_jobs, name='saved-jobs'),
    path('cancel/request/<id>/',cancel_request, name='cancel-request'),
]

jobseeker/models.py
from django.db import models

from employer.models import Job
from portal.models import User
from django.urls import reverse

class JobSeekerProfile(models.Model):
    jobseeker = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    resume = models.FileField(null=True, upload_to='user_resume')
    
    def __str__(self):
        return f'Профиль - {self.jobseeker}'


    class Meta:
        verbose_name = "Профиль соискателя"
        verbose_name_plural = "Профиль соискателей"
    

class JobSeekerRequests(models.Model):
    requests = models.ForeignKey(User, on_delete=models.CASCADE, related_name='requests')
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    status = models.CharField(max_length=80, default="Ожидание встречи с работодателем")    

    def __str__(self):
        return f'{self.requests} Запрос на работу {self.job}'
    
    def save(self, *args, **kwargs):
        super(JobSeekerRequests, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Запрос соискателя"
        verbose_name_plural = "Запросы соискателя"


class JobSeekerSaveJob(models.Model):
    saved_job = models.ForeignKey(User, on_delete=models.CASCADE, related_name='saved_jobs')
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.saved_job}'
    
    def save(self, *args, **kwargs):
        super(JobSeekerSaveJob, self).save(*args, **kwargs)

    
    class Meta:
        verbose_name = "Сохраненная вакансия"
        verbose_name_plural = "Сохраненные вакансии"

jobseeker/forms.py
from django import forms

from portal.models import User
from .models import JobSeekerProfile


class JobSeekerProfileForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['full_name', 'email']
    
    def __init__(self, *args, **kwargs):
        super(JobSeekerProfileForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].label = "Фамилия Имя Отчество"
        self.fields['email'].label = "Электронная почта"

        
class JobSeekerResumeForm(forms.ModelForm):
    
    class Meta:
        model = JobSeekerProfile
        fields = ['resume'] 
    
    def __init__(self, *args, **kwargs):
        super(JobSeekerResumeForm, self).__init__(*args, **kwargs)
        self.fields['resume'].label = "Файл резюме (PDF)"

portal/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(
        label='Фамилия Имя Отчество',
        widget=forms.TextInput(
           attrs={'placeholder': 'Введите ФИО',}
           )
        )
    email = forms.EmailField(
        label='Электронная почта',
        widget=forms.EmailInput(
           attrs={'placeholder': 'Введите e-mail'}
            )
        )
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Введите пароль'}
            )
        )
    password2 = forms.CharField(
        label='Подтверждение пароля',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Подтвердите пароль'}
            )
        )
    
    error_messages = {
        'password_mismatch': 'Пароли не совпадают',
    }
    
    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Эта почта существует в платформе')
        return email

    class Meta:
        model = User
        fields=['full_name', 'email', 'password1', 'password2']


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        label='Электронная почта',
        widget=forms.EmailInput(
           attrs={'placeholder': 'Введите e-mail'}
        )
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Введите пароль'}
        )
    )

jobseeker/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.http import Http404

from .forms import JobSeekerProfileForm, JobSeekerResumeForm
from .models import JobSeekerProfile, JobSeekerRequests, JobSeekerSaveJob
from employer.models import Job, JobRequests


def is_jobseeker(user):
    try:
        if not user.is_jobseeker:
            raise Http404
        return True
    except:
        raise Http404


@user_passes_test(is_jobseeker)
@login_required
def jobseeker_profile(request):
    JobSeekerProfile.objects.get_or_create(jobseeker=request.user)
    if request.method == 'POST':
        profile_form = JobSeekerProfileForm(
            request.POST,
            instance=request.user
        )
        resume_form = JobSeekerResumeForm(
            request.POST,
            request.FILES,
            instance=request.user.profile
        )
        if profile_form.is_valid() and resume_form.is_valid():
            profile_form.save()
            resume_form.save()
            messages.success(request, 'Ваш профиль обновлен')
            return redirect('jobseeker-profile')
    else: 
        profile_form = JobSeekerProfileForm(instance=request.user)
        resume_form = JobSeekerResumeForm(
            instance=request.user.profile
        )
    context = {
        'profile_form' : profile_form,
        'resume_form' : resume_form,
    }
    return render(request, 'jobseeker_profile.html', context)


@login_required
@user_passes_test(is_jobseeker)
def request_job(request, id):
    if request.user.requests.filter(job=id):
        messages.warning(
            request,
            'Вы уже отправили свое резюме по этому объявлению.'
        )
        return redirect('home-page')
    if not request.user.profile.resume:
        messages.info(request, 'Сначала загрузите свое резюме.')
        return redirect('jobseeker-profile')
    job = get_object_or_404(Job, id=id)
    req = JobSeekerRequests(
        job=job,
        requests=request.user
    )
    req.save()
    req_to_employer = JobRequests(
        jobseeker=request.user,
        job=job,
        resume_url=request.user.profile.resume.url,
        employer=job.company,
        
    )
    req_to_employer.save()
    messages.success(request, 'Ваше резюме отправлено')
    return redirect('home-page')


@login_required
@user_passes_test(is_jobseeker)
def jobseeker_requests(request):
    requests = request.user.requests.all()
    if not requests:
        messages.info(request, 'Вы еще не отправили запрос')
    return render(request, 'jobseeker_requests.html', {'requests':requests})


@login_required
@user_passes_test(is_jobseeker)
def save_job(request, id):
    if request.user.saved_jobs.filter(job=id):
        messages.warning(request, 'Эта вакансия уже сохранена.')
        return redirect('home-page')
    job = get_object_or_404(Job, id=id)
    save_job = JobSeekerSaveJob(job=job, saved_job=request.user)
    save_job.save()
    messages.success(request, 'Вы сохранили вакансию')
    return redirect('home-page')


@login_required
@user_passes_test(is_jobseeker)
def jobseeker_saved_jobs(request):
    jobs = request.user.saved_jobs.all()
    return render(request, 'jobseeker_saved_jobs.html', {'jobs':jobs})


def cancel_request(request, id):
    jobseeker_req = get_object_or_404(request.user.requests, id=id)
    #request sent to employer
    if jobseeker_req.status != 'Подтверждено':
        jobseeker_req = request.user.requests.filter(id=id).delete()
        employer_req = JobRequests.objects.filter(id=id).delete()
        messages.success(request, 'Ваш запрос был отменен')
    else:
        raise Http404
    return redirect('jobseeker-requests')

jobseeker/templates/jobseeker_profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    label {
        margin-bottom: 10px;
        font-weight: 700;
    }
    #id_full_name, #id_email {
        margin-bottom: 10px;
    }
    label {
        cursor: pointer;
    }

    #id_resume {
        color: transparent;
    }
    #id_resume::-webkit-file-upload-button {
        visibility: hidden;
    }
    #id_resume::before {
        content: 'Загрузить файл ➤';
        color: #fff;
        display: inline-block;
        background: #106cf6;
        border-radius: 3px;
        padding: 5px 8px;
        outline: none;
        white-space: nowrap;
        -webkit-user-select: none;
        cursor: pointer;
        font-weight: 700;
        font-size: 10pt;
    }
    #id_resume:hover::before {
        border-color: #fff;
    }
    #id_resume:active {
        outline: 0;
    }
    #id_resume:active::before {
        background: #106cf6;
    }

</style>
<div class="">
    <legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-user"></i> Мой профиль</legend>

    <form class="content-section border border-0 shadow p-3 bg-body rounded" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ profile_form|crispy }}
            {{ resume_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="button is-blue mt-3 mb-3" style="width:100%;" type="submit">Обновить</button>
        </div>
        <a href="{% static './template.docx' %}" style="font-weight: 700;" download target="_blank" class="blue-link">Скачать шаблон резюме</a>
    </form>
</div>

{% endblock %}

jobseeker/templates/jobseeker_requests.html
{% extends "base.html" %}
{% block content %}

<legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-user-clock"></i> Мои запросы</legend>


{% for request in requests %}
{% if request.status == 'Подтверждено' %}
<div class="content-section border border-0 shadow bg-body rounded">
  <div class="card-body">
    <h3><b>Компания: </b> {{ request.job.company }}</h3>
    <p><b>Вакансия: </b>{{ request.job }}</p>
    <div class="mb-3">
      <a href="{% url 'job-detail' request.job.id %}" class="button is-blue is-small">Посмотреть вакансию</a>
    </div>
  </div>
</div>
{% else %}
<div class="content-section border border-0 shadow bg-body rounded">
  <div class="card-body">
    <h3><b>Компания: </b> {{ request.job.company }}</h3>
    <p><b>Вакансия: </b>{{ request.job }}</p>
    <p><a class="btn btn-danger" target="_blank" href="{% url 'cancel-request' request.id %}">Отменить запрос</a></p>
  </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

jobseeker/templates/jobseeker_saved_jobs.html
{% extends "base.html" %}
{% block content %}

<legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-star"></i> Избранное</legend>


    <div class="row">
      {% for job in jobs %}
      <div class="col-md-6 mb-3">
        <div class="content-section border border-0 shadow bg-body rounded h-100">
          <div class="card-body">
            <h6 class="mb-3">{{ job.job.title }}</h6>
            <a class="button is-blue d-block text-center" href="{% url 'job-detail' job.job.id %}">Посмотреть</a> 
          </div>
        </div>
      </div>
      {% endfor %}

    </div>

{% endblock %}