OnlineJobPortalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from portal.forms import UserLoginForm
from portal.views import (
    banner_page,
    jobseeker_register,
    employer_register,
    login_request,
    home_page,
    job_detail,
    search,
    filter_by_category
)



urlpatterns = [
    path('emoloyer/', include('employer.urls')),
    path('user/', include('jobseeker.urls')),
    path('', banner_page, name='banner-page'),
    path('job/list/', home_page, name='home-page'),
    path('admin/', admin.site.urls),
    path('register/', jobseeker_register, name='register'),
    path('employer/register/', employer_register, name='employer-register'),
    path('login/', login_request, name='login'),
    path('job/detail/<int:id>/', job_detail, name='job-detail'),
    path('search/', search, name='search'),
    path('filter/category/<category>', filter_by_category, name='filter-by-category'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

employer/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView



from .views import (employer_home,
                   employer_profile,
                   employer_jobs,
                   employer_create_job,
                   accepted_status,
                   hired_status,
                   delete_request,
                   )


urlpatterns = [
    path('home/', employer_home , name='employer-home'),
    path('profile/', employer_profile , name='employer-profile'),
    path('jobs/', employer_jobs , name='employer-jobs'),
    path('create/job/', employer_create_job , name='employer-create-job'),
    path('accept/request/<int:id>/', accepted_status, name='accept-status'),
    path('hire/request/<int:id>/', hired_status, name='hire-status'),
    path('delete/request/<int:id>/', delete_request, name='delete-request'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

employer/models.py
import datetime
import humanize

from PIL import Image
from django.db import models
from django.utils import timezone
from django_jalali.db import models as jmodels

from portal.models import  User, Category


class Company(models.Model):
    employer = models.OneToOneField(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    co_introduction = models.TextField()
    logo = models.ImageField(default='default.png', upload_to='co-logo')
    link  = models.CharField(max_length=80)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super(Company, self).save(*args, **kwargs)

        img = Image.open(self.logo.path)

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компании"


class Job(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='jobs')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    title = models.CharField(max_length=80)
    location = models.CharField(max_length=80)
    created_date = models.DateTimeField(default=datetime.datetime.now(), blank=True)
    experience_choices = (
        ('Нет опыта работы','Нет опыта работы'),
        ('1-3 года', '1-3 года'),
        ('3-6 года', '3-6 года'),
        ('6 и выше', '6 и выше'),
    )
    experience = models.CharField(max_length=80, choices=experience_choices)
    salary_choices = (
        ('Не указано', 'Не указано'),
        ('от 100 000 до 190 000 тг.', 'от 100 000 до 190 000 тг.'),
        ('от 200 000 до 290 000 тг.', 'от 200 000 до 290 000 тг.'),
        ('от 300 000 до 390 000 тг.', 'от 300 000 до 390 000 тг.'),
        ('от 400 000 до 490 000 тг.', 'от 400 000 до 490 000 тг.'),
        ('от 500 000 и выше', 'от 500 000 и выше'),
    )
    salary = models.CharField(
        max_length=80, choices=salary_choices
    )
    cooperation_choices = (
        ('Полная занятость', 'Полная занятость'),
        ('Частичная занятость', 'Частичная занятость'),
        ('Удаленная работа', 'Удаленная работа'),
        ('Стажировка', 'Стажировка'),
        ('Производственная практика', 'Производственная практика'),
    )
    cooperation_type = models.CharField(
        max_length=80, choices=cooperation_choices
    )
    job_description = models.TextField()
    skills_required = models.CharField(max_length=80)
    '''
    military_choices = (
        ('Военнообязанный', 'Военнообязанный'),
        ('Есть военный билет', 'Есть военный билет'),
    )
    military_service = models.CharField(
        max_length=80, choices=military_choices
    )
    '''
    degree_choices = (
        ('Не имеет значения', 'Не имеет значения'),
        ('Диплом ТиПО', 'Диплом ТиПО'),
        ('Диплом бакалавра', 'Диплом бакалавра'),
        ('Диплом магистра', 'Диплом магистра'),
        ('Диплом Phd', 'Диплом Phd'),
    )
    degree = models.CharField(max_length=80, choices=degree_choices)

    def __str__(self):
        return self.title
    

    class Meta:
        verbose_name = "Вакансия"
        verbose_name_plural = "Вакансии"
    
    
class JobRequests(models.Model):
    employer = models.ForeignKey(Company, on_delete=models.CASCADE)
    jobseeker = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    resume_url = models.CharField(max_length=100)
    accepted = models.BooleanField(default=False)
    hired = models.BooleanField(default=False)
    viewed = models.BooleanField(default=False)
    
    def __str__(self):
        return f'Запрос компании {self.jobseeker} на работу {self.job}'
    
    def save(self, *args, **kwargs):
        super(JobRequests, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name = "Запрос на вакансию"
        verbose_name_plural = "Запросы на вакансию"

    

portal/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from portal.managers import MyUserManager


class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True)
    full_name = models.CharField(max_length=100)
    
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_jobseeker = models.BooleanField(default=True)
    
    objects = MyUserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    def __str__(self):
        return self.full_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

class Category(models.Model):
    name = models.CharField(max_length=80)

    def __str__(self):
       return self.name
    
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

portal/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(
        label='Фамилия Имя Отчество',
        widget=forms.TextInput(
           attrs={'placeholder': 'Введите ФИО',}
           )
        )
    email = forms.EmailField(
        label='Электронная почта',
        widget=forms.EmailInput(
           attrs={'placeholder': 'Введите e-mail'}
            )
        )
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Введите пароль'}
            )
        )
    password2 = forms.CharField(
        label='Подтверждение пароля',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Подтвердите пароль'}
            )
        )
    
    error_messages = {
        'password_mismatch': 'Пароли не совпадают',
    }
    
    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Эта почта существует в платформе')
        return email

    class Meta:
        model = User
        fields=['full_name', 'email', 'password1', 'password2']


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        label='Электронная почта',
        widget=forms.EmailInput(
           attrs={'placeholder': 'Введите e-mail'}
        )
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Введите пароль'}
        )
    )

portal/views.py
from datetime import datetime, timezone

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import Http404

from employer.models import Job
from jobseeker.models import JobSeekerRequests
from .forms import UserRegisterForm, UserLoginForm
from .models import User

def banner_page(request):
    return render(request, "banner.html")

def home_page(request):
    jobs = Job.objects.order_by('-created_date').all()
    now = datetime.now(timezone.utc)
    for i in jobs:
        get_days = now - i.created_date
        if get_days.days > 1:
            i.created_date = f'{get_days.days} дней'
    return render(request, 'home_page.html', {'jobs':jobs})


def job_detail(request, id):
    job = get_object_or_404(Job, id=id)
    return render(request, 'job_detail.html', {'job':job})


def employer_register(request):
    if request.user.is_authenticated:
            raise Http404
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                    data['email'],
                    data['full_name'],
                    data['password1'],
            )
            user.is_jobseeker = False
            user.save()
            messages.success(
                request, 'Регистрация прошла успешно! Пройдите авторизацию'
            )
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'employer/register.html', {'form':form})


def jobseeker_register(request):
    if request.user.is_authenticated:
            raise Http404
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                    data['email'],
                    data['full_name'],
                    data['password1'],
            )
            user.save()
            messages.success(
                request, 'Регистрация прошла успешно! Пройдите авторизацию'
            )
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'jobseeker/register.html', {'form':form})


def login_request(request):
    if request.user.is_authenticated:
        raise Http404
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, email=data['email'], password=data['password']
            )
            if user is not None:
                login(request, user)
                if user.is_jobseeker:
                    return redirect('home-page')
                elif not user.is_jobseeker:
                    return redirect('employer-home')
            else:
                messages.success(request, 'Неправильный логин или пароль')
                return redirect('login')
    form = UserLoginForm()
    return render(request, 'login.html', {'form':form})



def search(request):
    query = request.GET.get('q')
    resaults =  Job.objects.filter(title__icontains=query).all()
    now = datetime.now(timezone.utc)
    for i in resaults:
        get_days = now - i.created_date
        if get_days.days > 1:
            i.created_date = f'{get_days.days} дней'
    return render(request, 'home_page.html', {'jobs':resaults})


def filter_by_category(request, category):
    resaults = Job.objects.filter(category__name=category).all()
    now = datetime.now(timezone.utc)
    for i in resaults:
        get_days = now - i.created_date
        if get_days.days > 1:
            i.created_date = f'{get_days.days} дней'
    return render(request, 'home_page.html', {'jobs':resaults})

portal/templates/banner.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static './css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './css/style.css' %}">
    <link rel="shortcut icon" href="{% static './img/favicon.svg' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>IT Job Need</title>
</head>
<body>
    <section id="main">
        <div class="container">
            <div class="row">
              <div class="col-md-7">
                <div class="relative-content">
                    <h1><span class="blue-text">Здесь Вы можете найти работу.</span> Вакансии во всем Казахстане 🇰🇿</h1>
                    <p><strong class="blue">jobneed.it</strong> — сервис, который помогает найти работу в сфере информационных технологий! Создавайте резюме и откликайтесь на вакансии. Набирайте сотрудников и публикуйте вакансии. Больше актуальных вакансий здесь. Найдите свою новую работу сегодня.</p>
                    <a href="{% url 'home-page' %}" class="button is-blue">Найти работу&nbsp; <i class="fa-solid fa-briefcase"></i></a>
                </div>
              </div>
              <div class="main-image col-md-5">
                <img src="{% static './img/main.svg' %}" class="w-100 d-block" alt="Main">
              </div>
            </div>
        </div>
    </section>
</body>
</html>

portal/templates/base.html
{% load static %}
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static './css/main.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static './css/style.css' %}">
  <link rel="shortcut icon" href="{% static './img/favicon.svg' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--<script src="https://lidrekon.ru/slep/js/jquery.js"></script>
  <script src="https://lidrekon.ru/slep/js/uhpv-full.min.js"></script>-->
  {% if title %}
  <title>{{title}}</title>
  {% else %}
  <title>Job need</title>
  {% endif %}
</head>
<style>
  .accordion-button:focus {
    box-shadow: none;
  }
</style>
<body>
<header class="navbar navbar-expand-lg navbar-light bg-primary blue-bottom-border mb-5 ">
  <div class="container">
    <a class="navbar-brand logo" href="{% url 'home-page' %}">
      <img src="{% static './img/logo.svg' %}" alt="Logo">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          {% if not user.is_jobseeker %}
            {% if user.company.jobs %}
            <li class="nav-item">
              <a class="header-link" href="{% url 'employer-home' %}">Запросы</a>
            </li>
            <li class="nav-item">
              <a class="header-link" href="{% url 'employer-jobs' %}">Вакансии компании</a>
            </li>
            <li class="nav-item">
              <a class="header-link" href="{% url 'employer-create-job' %}">Создать вакансию</a>
            </li>
            <li class="nav-item dropdown">
              <a class="header-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.email }}&nbsp;<i class="fa-solid fa-circle-dot"></i>
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'employer-profile' %}"><i class="fa-solid fa-building"></i>&nbsp;Профиль компании</a></li>
                <form method="post" action="{% url 'logout' %}">
                     {% csrf_token %}
                <li><button class="dropdown-item" type="submit"><i class="fa-solid fa-circle-xmark"></i>&nbsp;Выход</button></li>
                </form>    
              </ul>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="header-link" href="{% url 'employer-profile' %}">Профиль компании</a>
            </li>
                <form method="post" action="{% url 'logout' %}">
                 {% csrf_token %}
                <li><button class="dropdown-item" type="submit"><i class="fa-solid fa-circle-xmark"></i>&nbsp;Выход</button></li>
                </form>  
            {% endif %}
          {% endif %}
        {% if user.is_jobseeker %}
            <li class="nav-item">
              <a class="header-link" href="{% url 'home-page' %}">Вакансии</a> 
            </li>
            <li class="nav-item">
              <a class="header-link" href="{% url 'saved-jobs' %}">Избранное</a> 
            </li>
            <li class="nav-item">
              <a class="header-link" href="{% url 'jobseeker-requests' %}">Мои запросы</a>
            </li>
            <li class="nav-item dropdown">
              <a class="header-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.email }}&nbsp;<i class="fa-solid fa-circle-dot white-text"></i>
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'jobseeker-profile' %}"><i class="fa-solid fa-user"></i>&nbsp;Мой профиль</a></li>
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                <li><button class="dropdown-item" type="submit"><i class="fa-solid fa-circle-xmark"></i>&nbsp;Выход</button></li>
                </form>  
              </ul>
            </li>
        {% endif %}
        {% else %}
          <li class="nav-item">
            <a class="header-link" href="{% url 'employer-register' %}">Работодателям</a>
          </li>
          <li class="nav-item">
            <a class="header-link" href="{% url 'register' %}">Найти работу</a>
          </li>
          <li class="nav-item">
            <a class="header-link" href="{% url 'login' %}">Вход</a>
          </li>            
        {% endif %}
        <!--Версия для слабовидящих
          <li class="nav-item">
          <img id="specialButton" style="cursor:pointer; width: 28px; margin-left: 20px; margin-right: 25px; margin-top: 6px;" src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/OOjs_UI_icon_eye-progressive.svg/1024px-OOjs_UI_icon_eye-progressive.svg.png" alt="ВЕРСИЯ ДЛЯ СЛАБОВИДЯЩИХ" title="ВЕРСИЯ ДЛЯ СЛАБОВИДЯЩИХ" />
        </li>-->
      </ul>
      <form class="d-flex mt-3" action="{% url 'search' %}">
        <input name="q" data-filter="1" class="form-control border border-secondary me-2" type="search" aria-label="Search" placeholder="Поиск вакансии">
        <button class="btn btn-outline-light is-small" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-4">
            <legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-clipboard-list"></i> Категории</legend>
            <div class="content-section p-4 border border-0 shadow p-3 mb-5 bg-body rounded">           
                <div class="accordion accordion-flush" id="accordionFlushExample">
                  <div class="accordion-item">
                    <h2 class="accordion-header">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        <h4 class="text-center blue mb-0">Список категорий</h4>
                      </button>
                    </h2>
                    <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                      <div class="accordion-body">
                        {% for category in categories %}
                          <li class="list-group-item">
                            <small><a href="{% url 'filter-by-category' category %}">{{ category }}</a></small>
                          </li>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
                

            </div>
          </div>
          <div class="col-md-8">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
          </div>
          
        </div>
    </main>



    <footer class="d-flex flex-wrap justify-content-between align-items-center mt-5 pt-5 pb-5 bg-dark">
      <div class="container">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <img src="{% static './img/favicon.svg' %}" width="32px" alt="Logo">
          </a>
          <span class="mb-3 mb-md-0 text-white">jobneed.it © <span id="year"></span>. Разработчик: <a href="#" class="text-white" style="font-weight: 600; text-decoration: none;">Естаев Данат</a></span>
        </div>
      </div>
    </footer>
    <script src="{% static './js/bootstrap.bundle.min.js' %}"></script>
    <script>
      document.getElementById("year").innerHTML = new Date().getFullYear();
    </script>
</body>
</html>

portal/templates/home_page.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
<div class="">
  <legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-business-time"></i> Последние вакансии</legend>
  {% for job in jobs %}
  <article class="content-section border border-0 shadow bg-body rounded">
    <div class="row">
      <div class="col-md-2 text-center pt-4">
        <img class="account-img" src="{{ job.company.logo.url }}">
      </div>
      <div class="col-md-10">
        <span style="font-weight: 600;">{{ job.title }}</span>
        <span class="text-muted mr-1" style="font-size: small;" >
          {% if job.created_date|naturalday == 'today' %}
          <td>(Сегодня)</td>
          {% elif job.created_date|naturalday == 'yesterday' %}
          <td>(Вчера)</td>
          {% else %}
          <td >({{ job.created_date|naturaltime }})</td>
          {% endif %}
        </span><br>
        <span style="vertical-align:middle;font-size:small;" class="mb-3">Компания: {{ job.company }}</span><br>
        <i class="text-primary material-icons" style="vertical-align: middle;font-size: medium;">&#xe0c8;</i> 
        <span style="vertical-align:middle;font-size:small;">{{ job.location }} </span><br>
        <i class="text-primary material-icons" style="vertical-align: middle;font-size: medium;" >&#xe8f9;</i>
        <span style="vertical-align:middle;font-size:small;">{{ job.get_cooperation_type_display }}</span>
        <span  class="text-muted" style="font-size: small;vertical-align: middle;">(Заработная плата {{ job.get_salary_display }})</span>
        <div class="menu-block mb-3">
          <a class="button is-blue is-small" href="{% url 'save-job' job.id %}"><i class="fa-solid fa-star text-white"></i></a>
          <a class="button is-blue is-small" href="{% url 'job-detail' job.id %}">Подробнее</a>
          <a class="button is-blue is-small" href="{% url 'request-job' job.id %}">Откликнуться</a>
        </div>
      </div>
      </div>    
    <div style="width: 100%;">
    
  </article>
  {% endfor %}




<span style="margin-bottom: 50px; display: block;"></span>
</div>
{% endblock %}

portal/templates/job_detail.html
{% extends "base.html" %}
{% block content %}

<article class="content-section border border-0 shadow p-3  bg-body rounded">
  <div class="media-body">
    <div class="row">
      <div class="col-md-2">
        <img class="account-img" src="{{ job.company.logo.url }}">
      </div>
      <div class="col-md-10">
        <p style="font-size: 30px;" class="blue">{{ job.company }}</p>
        <small class="text-muted">Сайт компании: <a class="blue-link" href="{{ job.company.link }}">{{ job.company.link }}</a></small>
      </div>
    </div>
    
    <div class="article-metadata mt-2">
      </div>
      <h3 class="blue mt-3">{{ job.title }}</h3>
      <p>Категория: <span class="badge rounded-pill text-bg-primary">{{ job.category }}</span></p>
      <hr>
      <p>Опыт работы: <span class="badge rounded-pill text-bg-primary">{{ job.get_experience_display }}</span></p>

      <p>Расположение: <span class="badge rounded-pill text-bg-primary">{{ job.location }}</span></p>
      <p>Заработная плата: <span class="badge rounded-pill text-bg-primary">{{ job.get_salary_display }}</span></p>
      <p>Занятость: <span class="badge rounded-pill text-bg-primary">{{ job.get_cooperation_type_display }}</span></p>
    
      <legend class="mb-3 blue">О компании</legend>
      <p class="mb-3"><i>{{job.company.co_introduction}}</i></p>
      <legend class="mb-3 blue" >Описание работы</legend>
      <p class="article-content"><i>{{ job.job_description }}</i></p>
      <p>Навыки: <span class="badge rounded-pill text-bg-primary">{{ job.skills_required }}</span></p>
      <p>Образование: <span class="badge rounded-pill text-bg-primary">{{ job.get_degree_display }}</span></p>
      <hr>
      <div class="pt-2s pb-2">
        <a class="button is-blue is-small" href="{% url 'request-job' job.id %}">Откликнуться</a>
      </div>
  </div>      
</article>

{% endblock %}

portal/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    label {
        font-weight: 600;
        margin-top: 10px;
        margin-bottom: 10px;
    }
</style>
    <div class="blocck">
        <legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-right-to-bracket"></i> Вход в систему</legend>

        <form class="content-section border border-0 shadow p-3 bg-body rounded" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="mt-3 button is-blue" style="width:100%;" type="submit">Войти</button>
            </div>
        </form>
        <div class="pt-3">
            <p><small>Вы работодатель? <a class="blue-link" href="{% url 'employer-register' %}">пройти регистрацию</a></small></p>
            <p><small>Вы ищите работу? <a class="blue-link" href="{% url 'register' %}">пройти регистрацию</a></small></p>
        </div>
    </div>
{% endblock %}