OnlineJobPortalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from portal.forms import UserLoginForm
from portal.views import (
    banner_page,
    jobseeker_register,
    employer_register,
    login_request,
    home_page,
    job_detail,
    search,
    filter_by_category
)



urlpatterns = [
    path('emoloyer/', include('employer.urls')),
    path('user/', include('jobseeker.urls')),
    path('', banner_page, name='banner-page'),
    path('job/list/', home_page, name='home-page'),
    path('admin/', admin.site.urls),
    path('register/', jobseeker_register, name='register'),
    path('employer/register/', employer_register, name='employer-register'),
    path('login/', login_request, name='login'),
    path('job/detail/<int:id>/', job_detail, name='job-detail'),
    path('search/', search, name='search'),
    path('filter/category/<category>', filter_by_category, name='filter-by-category'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

employer/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView



from .views import (employer_home,
                   employer_profile,
                   employer_jobs,
                   employer_create_job,
                   accepted_status,
                   hired_status,
                   delete_request,
                   )


urlpatterns = [
    path('home/', employer_home , name='employer-home'),
    path('profile/', employer_profile , name='employer-profile'),
    path('jobs/', employer_jobs , name='employer-jobs'),
    path('create/job/', employer_create_job , name='employer-create-job'),
    path('accept/request/<int:id>/', accepted_status, name='accept-status'),
    path('hire/request/<int:id>/', hired_status, name='hire-status'),
    path('delete/request/<int:id>/', delete_request, name='delete-request'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

employer/models.py
import datetime
import humanize

from PIL import Image
from django.db import models
from django.utils import timezone
from django_jalali.db import models as jmodels

from portal.models import  User, Category


class Company(models.Model):
    employer = models.OneToOneField(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    co_introduction = models.TextField()
    logo = models.ImageField(default='default.png', upload_to='co-logo')
    link  = models.CharField(max_length=80)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super(Company, self).save(*args, **kwargs)

        img = Image.open(self.logo.path)

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компании"


class Job(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='jobs')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    title = models.CharField(max_length=80)
    location = models.CharField(max_length=80)
    created_date = models.DateTimeField(default=datetime.datetime.now(), blank=True)
    experience_choices = (
        ('Нет опыта работы','Нет опыта работы'),
        ('1-3 года', '1-3 года'),
        ('3-6 года', '3-6 года'),
        ('6 и выше', '6 и выше'),
    )
    experience = models.CharField(max_length=80, choices=experience_choices)
    salary_choices = (
        ('Не указано', 'Не указано'),
        ('от 100 000 до 190 000 тг.', 'от 100 000 до 190 000 тг.'),
        ('от 200 000 до 290 000 тг.', 'от 200 000 до 290 000 тг.'),
        ('от 300 000 до 390 000 тг.', 'от 300 000 до 390 000 тг.'),
        ('от 400 000 до 490 000 тг.', 'от 400 000 до 490 000 тг.'),
        ('от 500 000 и выше', 'от 500 000 и выше'),
    )
    salary = models.CharField(
        max_length=80, choices=salary_choices
    )
    cooperation_choices = (
        ('Полная занятость', 'Полная занятость'),
        ('Частичная занятость', 'Частичная занятость'),
        ('Удаленная работа', 'Удаленная работа'),
        ('Стажировка', 'Стажировка'),
        ('Производственная практика', 'Производственная практика'),
    )
    cooperation_type = models.CharField(
        max_length=80, choices=cooperation_choices
    )
    job_description = models.TextField()
    skills_required = models.CharField(max_length=80)
    '''
    military_choices = (
        ('Военнообязанный', 'Военнообязанный'),
        ('Есть военный билет', 'Есть военный билет'),
    )
    military_service = models.CharField(
        max_length=80, choices=military_choices
    )
    '''
    degree_choices = (
        ('Не имеет значения', 'Не имеет значения'),
        ('Диплом ТиПО', 'Диплом ТиПО'),
        ('Диплом бакалавра', 'Диплом бакалавра'),
        ('Диплом магистра', 'Диплом магистра'),
        ('Диплом Phd', 'Диплом Phd'),
    )
    degree = models.CharField(max_length=80, choices=degree_choices)

    def __str__(self):
        return self.title
    

    class Meta:
        verbose_name = "Вакансия"
        verbose_name_plural = "Вакансии"
    
    
class JobRequests(models.Model):
    employer = models.ForeignKey(Company, on_delete=models.CASCADE)
    jobseeker = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    resume_url = models.CharField(max_length=100)
    accepted = models.BooleanField(default=False)
    hired = models.BooleanField(default=False)
    viewed = models.BooleanField(default=False)
    
    def __str__(self):
        return f'Запрос компании {self.jobseeker} на работу {self.job}'
    
    def save(self, *args, **kwargs):
        super(JobRequests, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name = "Запрос на вакансию"
        verbose_name_plural = "Запросы на вакансию"

    

employer/forms.py
from django import forms

from .models import Company, Job, Category


class EmployerProfileForm(forms.ModelForm):

    class Meta:
        model = Company
        fields=['category', 'name', 'co_introduction', 'logo', 'link']

    def __init__(self, *args, **kwargs):
        super(EmployerProfileForm, self).__init__(*args, **kwargs)
        self.fields['category'].label = "Укажите чем занимается ваша компания"
        self.fields['name'].label = "Название компании"
        self.fields['co_introduction'].label = "Представьте свою компанию"
        self.fields['logo'].label = "Загрузите логотип"
        self.fields['link'].label = "Введите ссылку на сайт компании"

class EmployerJobCreationForm(forms.ModelForm):
    
    class Meta:
        model = Job
        fields = [
            'category', 'title', 'location',
            'experience', 'salary', 'cooperation_type',
            'job_description', 'skills_required',
            'degree',
        ]
    
    def __init__(self, *args, **kwargs):
        super(EmployerJobCreationForm, self).__init__(*args, **kwargs)
        self.fields['category'].label = "Выберите сферу деятельности"
        self.fields['title'].label = "Введите названия вакансии"
        self.fields['location'].label = "Введите местоположение вашей компании"
        self.fields['experience'].label = "Требуемый опыт работы"
        self.fields['salary'].label = "Заработная плата"
        self.fields['cooperation_type'].label = "Занятость"
        self.fields['job_description'].label = "Описание работы"
        self.fields['skills_required'].label = "Требуемые навыки"
        self.fields['degree'].label = "Образование"

employer/views.py
from datetime import datetime, timezone

from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test

from .forms import EmployerJobCreationForm, EmployerProfileForm
from .models import Company, JobRequests


def is_employer(user):
    try:
        if user.is_jobseeker:
            raise Http404
        return True
    except:
        raise Http404


@user_passes_test(is_employer)
@login_required
def employer_home(request):
    try:
        requests = JobRequests.objects.filter(
            employer=request.user.company, accepted=False
            ).all()
        accepted_requests = JobRequests.objects.filter(
            employer=request.user.company, accepted=True
            ).all()
    except Company.DoesNotExist:
        messages.success(
            request,
            'Чтобы получить доступ к другим разделам, сначала заполните следующую информацию.'
        )
        return redirect('employer-profile')
    context = {
        'requests':requests,
        'accepted_requests': accepted_requests,
        }
    return render(request, 'employer_home.html', context)


@user_passes_test(is_employer)
@login_required
def employer_profile(request):
    try:
        if request.method == 'POST':
            form = EmployerProfileForm(
                request.POST, request.FILES, instance=request.user.company
                )
            if form.is_valid():
                instance = form.save(commit=False)
                instance.employer = request.user
                instance.save()
                messages.success(request, 'Ваш профиль был обновлен.')
                return redirect('employer-profile')
        form = EmployerProfileForm(instance=request.user.company)
    except Company.DoesNotExist:
            # if user is new and has not a profile
            if request.method == 'POST':
                form = EmployerProfileForm(request.POST)
                if form.is_valid():
                    instance = form.save(commit=False)
                    instance.employer = request.user
                    instance.save()
                    messages.success(request, 'Ваш профиль создан')
                    messages.success(request, 'Чтобы создать вакансию, выберите новый вариант объявления в верхнем меню.')
                    return redirect('employer-profile')
            form = EmployerProfileForm()
    return render(request, 'profile.html', {'form':form})


@user_passes_test(is_employer)
@login_required
def employer_jobs(request):
    try:
        jobs = request.user.company.jobs.all()
        now = datetime.now(timezone.utc)
        for i in jobs:
            get_days = now - i.created_date
            if get_days.days > 1:
                i.created_date = f'{get_days.days} дней'
        requests = JobRequests.objects.filter(employer=request.user.company)
    except Company.DoesNotExist:
        return redirect('employer-home')
    return render(request, 'jobs.html', {'jobs':jobs, 'number':len(requests)})


@user_passes_test(is_employer)
@login_required
def employer_create_job(request):
    """ create a job and publishe it to the portal"""
    try:
        if request.method == 'POST':
            form = EmployerJobCreationForm(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.company = request.user.company
                instance.save()
                messages.success(request, 'Ваше вакансия опубликована')
                return redirect('job-detail', id=instance.id)
        elif request.method == 'GET':
            form = EmployerJobCreationForm()
    except Company.DoesNotExist:
        raise Http404
    return render(request, 'create_job.html', {'form':form})


def accepted_status(request, id):
    req = JobRequests.objects.filter(id=id).first()
    req.accepted = True
    req.save()
    return redirect('employer-home')


def hired_status(request, id):
    req = JobRequests.objects.filter(id=id).first()
    req.hired = True
    return redirect('employer-home')


def delete_request(request, id):
    req = JobRequests.objects.filter(id=id).delete()
    return redirect('employer-home')

employer/templates/create_job.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<style>
    label {
        margin-top: 10px;
        margin-bottom: 10px;
        font-weight: 600;
    }
    
</style>
<div class="blocck">
    <legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-file-circle-plus"></i> Создать вакансию</legend>

    <form class="content-section border border-0 shadow p-3 bg-body rounded" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}
        </fieldset>
        <div class="mt-3 form-group">
            <button class="button is-blue" style="width:100%;" type="submit">Опубликовать вакансию</button>
        </div>
    </form>
</div>

{% endblock %}

employer/templates/employer_home.html
{% extends "base.html" %}
{% block content %}
<div class="blocck">
<legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-bell"></i> Новые запросы</legend>
<div class="content-section border border-0 shadow p-3 bg-body rounded table-responsive">
  <table class="table table-sm" style="text-align: center;">
    <thead>
        <tr>
            <th scope="col">ФИО</th>
            <th scope="col">Вакансия</th>
            <th scope="col">Резюме</th>
            <th scope="col" colspan="2">Действия</th>
        </tr>
    </thead>
    {% for request in requests %}
    <tbody>
      <tr>
        <td>{{ request.jobseeker }}</td>
        <td><a class="blue-link" href="{% url 'job-detail' request.job.id%}"> {{ request.job }}</a></td>
        <td><a
          target="_blank" class="btn btn-primary btn-sm" href="{{ request.resume_url }}"><i class="fa-solid fa-file"></i> Резюме</a>
        </td>
        <td>
          <a class="btn btn-success btn-sm"
           href="{% url 'accept-status' request.id %}"><i class="fa-solid fa-check"></i> Принять</a>
        </td>
        <td><a class="btn btn-danger btn-sm"
          href="{% url 'delete-request' request.id %}"><i class="fa-solid fa-ban"></i> Удалить</a></td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
</div>
<legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-check"></i> Принятые сотрудники</legend>

<div class="content-section border border-0 shadow p-3 bg-body rounded">
  <table class="table table-sm">
    <thead>
        <tr>
            <th scope="col">ФИО</th>
            <th scope="col">Вакансия</th>
            <th scope="col">Резюме</th>
        </tr>
    </thead>
    <tbody>
      {% for request in accepted_requests %}
      {% if request.hired %}
      <tr>
        <td>{{ request.jobseeker }}</td>
        <td><a href=""> </a>{{ request.job }}</td>
        <td>
          <p>Уволен</p>
        </td>
      </tr>
      {% else %}
      <tr>
        <td>{{ request.jobseeker }}</td>
        <td><a href=""> </a>{{ request.job }}</td>
        <td>
          <a  class="btn btn-danger btn-sm" 
           href="{% url 'delete-request' request.id  %}"><i class="fa-solid fa-trash-can"></i> Уволить</a>
        </td>
      </tr>

    </tbody>
    {% endif %}
    {% endfor %}
    
  </table>
</div>

{% endblock %}

employer/templates/jobs.html
{% extends "base.html" %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block content %}

<div class="blocck">
  <legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-building"></i> Вакансии компании</legend>
  <div class="content-section border border-0 shadow p-3 bg-body rounded">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Наименование вакансии</th>
          <th scope="col">Дата публикации</th>
          <th scope="col">Количество запросов</th>
          <th scope="col">Действие</th>
        </tr>
      </thead>
      <tbody>
        {% for job in jobs %}             
          <tr>
            <td>{{ job.title }}</td>
            {% if job.created_date|naturalday == 'today' %}
            <td>Сегодня</td>
            {% elif job.created_date|naturalday == 'yesterday' %}
            <td>Вчера</td>
            {% elif job.created_date|naturalday == 'tomorrow' %}
            <td>Завтра</td>
            {% else %}
            <td >{{ job.created_date|naturaltime }}</td>
            {% endif %}
            <td>{{ number }}</td>
            <form method="post" action="{% url 'delete-request' id=job.id %}">
              {% csrf_token %}
              <td><button type="submit" class="btn btn-danger">Удалить</button></td>

            </form>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

employer/templates/profile.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<style>
    label {
        margin-top: 10px;
        margin-bottom: 10px;
        font-weight: 600;
    }
    #id_logo {
        color: transparent;
    }
    #id_logo::-webkit-file-upload-button {
        visibility: hidden;
    }
    #id_logo::before {
        content: 'Загрузить фото ➤';
        color: #fff;
        display: inline-block;
        background: #106cf6;
        border-radius: 3px;
        padding: 5px 8px;
        outline: none;
        white-space: nowrap;
        -webkit-user-select: none;
        cursor: pointer;
        font-weight: 700;
        font-size: 10pt;
    }
    #id_logo:hover::before {
        border-color: #fff;
    }
    #id_logo:active {
        outline: 0;
    }
    #id_logo:active::before {
        background: #106cf6;
    }
</style>
<div class="blocck">
    <legend class="display-6 mb-4 blue" style="font-weight: 700;"><i class="fa-solid fa-building"></i> Профиль компании</legend>

    <form class="content-section border border-0 shadow p-3  bg-body rounded" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="mt-3 button is-blue" style="width:100%;" type="submit">Обновить информацию</button>
        </div>
    </form>
</div>

{% endblock %}